# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - ciruelo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install --upgrade pip==25.0.1 && pip install annotated-types==0.7.0 anyio==4.8.0 blinker==1.9.0 certifi==2025.1.31 click==8.1.8 colorama==0.4.6 distro==1.9.0 Flask==3.1.0 flask-cors==5.0.1 Flask-SQLAlchemy==3.1.1 greenlet==3.1.1 h11==0.14.0 httpcore==1.0.7 httpx==0.28.1 idna==3.10 itsdangerous==2.2.0 Jinja2==3.1.5 jiter==0.8.2 MarkupSafe==3.0.2 openai==1.64.0 pydantic==2.10.6 pydantic_core==2.27.2 PyMySQL==1.1.1 python-dotenv==1.0.1 sniffio==1.3.1 SQLAlchemy==2.0.38 tqdm==4.67.1 typing_extensions==4.12.2 Werkzeug==3.1.3
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_92083BB010BA4233BB8F5C6D17D70C17 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8FA20005843D473A9F4C8DBD9883300F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E5E959A960224674B5A4E51E466F3903 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'ciruelo'
          slot-name: 'Production'
          
